In [ ]:
#1.What is a Python library? Why do we use Python libraries?
A python library is a collection of reusable python code, modules, and Packages that provides pre-Written Functionality to
facilitates common programming tasks.There are several reasons for why python libraries are useful.
They are:
    -->Productivity
    -->Abstraction
    -->it is high level programming Language
    -->Interpreted Programming Language
    -->Dynamically Typed language
    -->General Purpose Language
    -->Free and Open Source Language
    -->Portability
    -->Extensibility
    -->more Flexibility
    -->standalization and Best Practices
    -->Protability and Reuse
    -->Advanced Capabilities
    -->Readability..,etc

In [ ]:
#2. What is the difference between Numpy array and List?
1.Python List
a.Storage- Python List is a Dynamically  data type. 
b.Functionality -It is a general Purpose Programming Language.
c.Speed-- Slower Due to Type checking and overhead
d.Memory--More due to overhead
2.Numpy Array
a.storage --Numpy Array is a  Fixed data type.
b.Functionality--It has mathematically and scientific operations.
c.Speed --Faster due to vectorized operations and no type checking.
d.Memory-- Optimized and efficient storage.


In [5]:
#3. Find the shape, size and dimension of the following array?
import numpy as np
arr=np.array([
               [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]
              ])
print("shape:",arr.shape)
print("size:",arr.size)
print("dimension:",arr.ndim)

shape: (3, 4)
size: 12
dimension: 2


In [6]:
#4. Write python code to access the first row of the following array?
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
first_row=arr[0]
print(first_row)


[1 2 3 4]


In [8]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
result=arr[2,3]
print(result)

12


In [9]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
odd_elements=arr[1::2, ::2]
print(odd_elements)

[[5 7]]


In [10]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np
matrix=np.random.random((3,3))
print(matrix)

[[0.78240565 0.73138029 0.90308778]
 [0.2659767  0.17727695 0.57936856]
 [0.24312039 0.01308909 0.53465582]]


In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn?
1.np.random.rand:-
--> Generate random numbers from uniform distribution within the half open interval [0.0,1.0). 
This means the value will be greater than or equal to '0' but strictly less than 1.
--> each value has an equal probability of being chosen within the range.
2.np.random.randn:-
--> Generate random numbers from the standard normal distribution ,with a mean of 0 and a varience of 1.
--> The values are distributed in a bell shaped curve with most value concentrated around the mean and fewer values further away.
                                                                                     

In [14]:
#examples
import numpy as np
uniform_matrix = np.random.rand(3, 3)
normal_matrix = np.random.randn(3, 3)
print("the uniform matrix is:",uniform_matrix)
print("the normal matrix is:",normal_matrix)

the uniform matrix is: [[0.16492148 0.05230471 0.86520387]
 [0.48392014 0.47395068 0.68508236]
 [0.6160089  0.09959812 0.87011701]]
the normal matrix is: [[-0.59531658  1.53383623 -1.13909494]
 [-0.41851257 -2.28714034  0.82456056]
 [-1.30114381  0.15255748 -1.50217963]]


In [15]:
#9. Write code to increase the dimension of the following array?
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
increased_dim_array = np.expand_dims(arr, axis=0)
print("Original dimension:\n",arr)
print("increased dimension array:\n",increased_dim_array)

Original dimension:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
increased dimension array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [16]:
#10. How to transpose the following array in NumPy?
#1.using the .T Transpose
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
transpose_array=arr.T
print(transpose_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [17]:
#2.using the np.transpose
import numpy as np
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
transposed_array = np.transpose(arr)
print(transposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [19]:
#11.consider the following matrix:
#1.index wise multiplication
#2.matrix multiplication
#3.add both the matrixs
#4.subtract matrix B from A
#5.divide matrix B by A
import numpy as np
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
C = A * B
print("1.index wise multiplication:\n", C)

D = np.dot(A, B.T)
print("2.matrix multiplication(D):\n", D)

E = A + B
print("3.Element wise Adding(E):\n", E)

F = A - B
print("4.Subtracting Matrixs(F):\n", F)

G = A/B
print("5.element wise dividing(G):\n", G)


1.index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
2.matrix multiplication(D):
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
3.Element wise Adding(E):
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
4.Subtracting Matrixs(F):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
5.element wise dividing(G):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12.  Which function in Numpy can be used to swap the byte order of an array?
The function in numpy that can be used to swap the byte orderof an array is byteswap().
It's a method of the ndarray objects and works on the underlying data into the memory.

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5],dtype = np.int32)
arr.byteswap(inplace = True)
print("Original Array:",arr)
print("Swapped Array:",arr)

Original Array: [16777216 33554432 50331648 67108864 83886080]
Swapped Array: [16777216 33554432 50331648 67108864 83886080]


In [27]:
#13.  What is the significance of the np.linalg.inv function?
import numpy as np
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("Original matrix:\n", A)
print("\nInverse of the matrix:\n", A_inv)
b = np.array([5, 7])
x = np.dot(A_inv, b)  
print("\nSolution to Ax = b (x):\n", x)


Original matrix:
 [[1 2]
 [3 4]]

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Solution to Ax = b (x):
 [-3.  4.]


In [ ]:
#14. What does the np.reshape function do, and how is it used?
The np.reshape function in numpy is used to chande the shapeof an existing arraywithout modifying its underlying data.
it allows you to reshape the array into a different arrangements of elements, as long as the total number elements remains the same.


In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print("Original array:", arr)
print("Reshaped array:", reshaped_arr)

Original array: [1 2 3 4 5 6]
Reshaped array: [[1 2 3]
 [4 5 6]]


In [ ]:
#15. What is broadcasting in Numpy?
Broadcasting in NumPy is a powerful mechanism that allows performing element-wise operations on arrays with different shapes
under certain conditions. It automatically expands the smaller array in a specific way to make it compatible with the 
larger array for the operation. This eliminates the need for explicit looping and often leads to efficient vectorized operations.

In [33]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
added = arr1 + arr2
print(added)


[[11 22 33]
 [14 25 36]]
